title: Tailwind & Jekyll rocks!
description: A starter kit for using Tailwind with Jekyll

plugins: [./_plugins/post.rb, ./_plugins/page.rb, ./_plugins/debug.rb, ./_plugins/i18n_filter.rb, jekyll-paginate-v2]

baseurl: ""
url: "https://objective-perlman-ff907b.netlify.com/"

# Permalink format (/blog/ is ignored for pages)
permalink: /:name/

collections:
  posts:
    permalink: /blog/:title/
    

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  locale: 'cs_CZ' 

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  sort_field: 'date'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  #permalink: '/blog/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0



exclude:
  - Gemfile
  - Gemfile.lock
  - feed.xml
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
