title: Tailwind Jekyll Starter Kit
description: A starter kit for using Tailwind with Jekyll
baseurl: ""
url: "https://objective-perlman-ff907b.netlify.com/"

# Permalink format (/blog/ is ignored for pages)
permalink: /blog/:title/

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# set some common post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

exclude:
  - Gemfile
  - Gemfile.lock
  - feed.xml
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
