title: Tailwind & Jekyll rocks!
description: A starter kit for using Tailwind with Jekyll

plugins: [./_plugins/post.rb, ./_plugins/page.rb, ./_plugins/debug.rb, 'octopress-paginate']

baseurl: ""
url: "https://objective-perlman-ff907b.netlify.com/"

# Permalink format (/blog/ is ignored for pages)
permalink: /:name/

collections:
  posts:
    permalink: /blog/:title/


# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

exclude:
  - Gemfile
  - Gemfile.lock
  - feed.xml
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
