backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
editor:
     preview: false
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Články" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Aktivní", name: "active", widget: "boolean", default: false}
      - {label: "Featured Image", name: "thumbnail", widget: "string"}
      - {label: "Hlavní text", name: "body", widget: "markdown"}
  - label: "Stránky"
    name: "pages"
    folder: '/'
    create: true
    format: frontmatter
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Aktivní", name: "active", widget: "boolean", default: false}
      - {label: "Hlavní text", name: "body", widget: "markdown", required: false}
      - label: Pozadí obsahu
        name: background
        required: false
        widget: select
        options:
          - { label: "Žádné", value: "none" }
          - { label: "Světlé", value: "bg-white" }
          - { label: "Tmavé", value: "bg-gray-800" }
      - {label: "Světlé texty", name: "", widget: "boolean", default: false, required: false}
      - {label: "Horní odsazení sekce", name: "margin-top", widget: "boolean", default: false, required: false}
      - {label: "Dolní odsazení bloků", name: "margin-bottom", widget: "boolean", default: false, required: false}
      - label: "Sekce nad hlavním obsahem"
        name: "sections-above"
        widget: "list"
        types:
          - label: Galerie
            name: gallery
            widget: object
            fields:
              - label: Nadpis
                name: header
                widget: string
                required: false
              - label: Nadpis - zarovnání
                name: header-alignment
                required: false
                widget: select
                options:
                  - { label: "Levá", value: "text-left" }
                  - { label: "Střed", value: "text-center" }
                  - { label: "Pravá", value: "text-right" }
              - label: Pozadí
                name: section-background
                required: false
                widget: select
                options:
                  - { label: "Žádné", value: "none" }
                  - { label: "Světlé", value: "bg-white" }
                  - { label: "Tmavé", value: "bg-gray-800" }
              - {label: "Světlé texty", name: "light-texts", widget: "boolean", default: false, required: false}
              - {label: "Odsazení", name: "margin-y", widget: "boolean", default: false, required: false}
              - label: Fotky
                name: images
                widget: list
                field: {label: Image, name: image, widget: image}
          - label: Mapa
            name: map
            widget: object
            fields:
              - {label: "Location", name: "location", widget: "map" }
          - label: Kontaktní formuláře
            name: contact-forms
            widget: object
            fields:
              - {label: Nadpis, name: header, widget: string, required: false}
              - label: Nadpis - zarovnání
                name: header-alignment
                required: false
                widget: select
                options:
                  - { label: "Levá", value: "text-left" }
                  - { label: "Střed", value: "text-center" }
                  - { label: "Pravá", value: "text-right" }
              - {label: Po odeslání přesměrovat, name: redirect-to, widget: string, required: false}
              - label: Pole formuláře
                name: form-fields
                widget: list
                fields:
                  - {label: Popis, name: label, widget: string, required: false}
                  - {label: Typ pole, name: "field-type", widget: "select", required: false, options: ["Input text", "Textarea"]}
          - label: Textové bloky
            name: text-blocks
            widget: object
            fields:
              - {label: Nadpis, name: header, widget: string, required: false}
              - label: Zarovnání nadpisu
                name: header-alignment
                required: false
                widget: select
                options:
                  - { label: "Levá", value: "text-left" }
                  - { label: "Střed", value: "text-center" }
                  - { label: "Pravá", value: "text-right" }
              - label: Bloky
                name: blocks
                widget: list
                fields:
                  - {label: Nadpis, name: header, widget: string, required: false}
                  - {label: Text, name: text, widget: markdown, required: false}
                  - label: Velikost textu
                    name: font-size
                    required: false
                    widget: select
                    options:
                      - { label: "Malé", value: "text-sm" }
                      - { label: "Normální", value: "" }
                      - { label: "Velké", value: "text-xl" }
                  - label: Zarovnání textu
                    name: text-alignment
                    required: false
                    widget: select
                    options:
                      - { label: "Levá", value: "text-left" }
                      - { label: "Střed", value: "text-center" }
                      - { label: "Pravá", value: "text-right" }
                  - {label: Desktop - šířka, name: "desktop-width-class", widget: "select", required: false, options: ["1/4", "1/3", "1/2", "2/3", "3/4", "full"]}
                  - {label: Tablet - šířka, name: "tablet-width-class", widget: "select", required: false, options: ["1/4", "1/3", "1/2", "2/3", "3/4", "full"]}
                  - {label: Mobile - šířka, name: "mobile-width-class", widget: "select", options: ["1/4", "1/3", "1/2", "2/3", "3/4", "full"]}
              - label: Pozadí
                name: section-background
                required: false
                widget: select
                options:
                  - { label: "Žádné", value: "none" }
                  - { label: "Světlé", value: "bg-white" }
                  - { label: "Tmavé", value: "bg-gray-800" }
              - label: Styl bloků
                name: block-style
                required: false
                widget: select
                options:
                  - { label: "Žádný", value: "none" }
                  - { label: "Podbarvený - světle šedá", value: "bg-gray-300 rounded" }
                  - { label: "Podbarvený - bílá", value: "bg-white shadow rounded" }
                  - { label: "Orámovaný", value: "border border-gray-300 rounded" }
              - {label: "Světlé texty", name: "light-texts", widget: "boolean", default: false, required: false}
              - {label: "Horní odsazení sekce", name: "padding-top", widget: "boolean", default: false, required: false}
              - {label: "Dolní odsazení bloků", name: "block-margin-bottom", widget: "boolean", default: false, required: false}
  - label: "Nastavení"
    name: "settings"
    files:
      - label: "Menu"
        name: "menu"
        file: "_data/navigation.yml"
        fields:
          - label: Odkazy
            name: links
            widget: list
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Url, name: url, widget: string}