backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
editor:
     preview: false
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Články" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Aktivní", name: "active", widget: "boolean", default: false}
      - {label: "Featured Image", name: "thumbnail", widget: "string"}
      - {label: "Hlavní text", name: "body", widget: "markdown"}
  - label: "Stránky"
    name: "pages"
    folder: '/'
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Aktivní", name: "active", widget: "boolean", default: false}
      - label: "Sekce nad hlavním obsahem"
        name: "sections-above"
        widget: "list"
        types:
          - label: "Carousel"
            name: "carousel"
            widget: object
            fields:
              - {label: Nadpis, name: header, widget: string, default: "Image Gallery"}
              - {label: Template, name: template, widget: string, default: "carousel.html", required: false}
              - label: Images
                name: images
                widget: list
                field: {label: Image, name: image, widget: image}
          - label: "Textové bloky"
            name: "text-blocks"
            widget: object
            fields:
              - {label: Template, name: template, widget: string, default: "blocks.html", required: false}
              - label: "Bloky"
                name: "blocks"
                widget: list
                fields:
                  - {label: Nadpis, name: header, widget: string, default: "Blocks"}
                  - {label: Text, name: text, widget: text, default: "Hello World"}
                  - {label: Desktop - šířka, name: "desktop-width-class", widget: "select", options: ["6", "12", "16", "24"]}
                  - {label: Tablet - šířka, name: "tablet-width-class", widget: "select", options: ["6", "12", "16", "24"]}
                  - {label: Mobile - šířka, name: "mobile-width-class", widget: "select", options: ["6", "12", "16", "24"]}
      - {label: "Hlavní text", name: "body", widget: "markdown"}
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field: {label: Image, name: image, widget: image}